#!/bin/sh
# build service.[ch] patch against original
# SDK sample

die() {
	local m="$1"

	echo "ERROR: $m" >&2
	exit 1
}

PSDK_SAMPLE="$1"

if [ -z "${PSDK_SAMPLE}" ]; then
	echo "usage: $0 psdk_sample"
	exit 1
fi

sed 's/\xd//' "${PSDK_SAMPLE}/service.c" > service.c.orig || die "sed service.c"
sed 's/\xd//' "${PSDK_SAMPLE}/service.h" > service.h.orig || die "sed service.h"

diff -urNp service.c.orig service.c >service.patch
diff -urNp service.h.orig service.h >>service.patch

rm service.c.orig service.h.orig

exit 0
